package edu.asu.cse360.team25.client.nurse;

import edu.asu.cse360.team25.protocol.PatientInfo;
import edu.asu.cse360.team25.protocol.exception.InvalidProtocolStateException;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FanjieLin
 */
public class NurseMainFrame extends javax.swing.JFrame {
    
    protected NurseClient nc;
    protected NurseServerConnection nsc;

 
    /**
     * Creates new form nurseSite
     */
    public NurseMainFrame(NurseClient nc) {
        initComponents();
        
        this.nc = nc;
    }
    
    public void showPatient() {
//        PatientInfo pi = nc.pi;
//        if (pi == null) {
//            return;
//        }
//        txt_pID.setText("ID: " + pi.getPatientID());
//        txt_pName.setText(pi.getName());
//        txt_pDoB.setText(pi.getBirthday());
        
        txt_pID.setText("0");
        txt_pName.setText("Amami Haruka");
        txt_pDoB.setText("Apr. 3");
        repaint();
    }

    protected void addPatientInfo(PatientInfo pi) {
        pi.setHeight(txt_height.getText());
        pi.setWeight(txt_weight.getText());
  //      pi.setDiastole(txt_high.getText());
  //      pi.setSystole(txt_systole.getText());
  //      pi.setHeartRate(txt_heartRate.getText());
        
    }
    
     protected void updatePatientInfo() {
        try {
            nsc.sendUpdatePatientProfile(txt_height.getText(), txt_weight.getText());
            JOptionPane.showMessageDialog(this,
                    "Patient profile update successfully.");
        } catch (IOException e) {
            return;
        } catch (InvalidProtocolStateException e) {
            System.out.println("Can not send UpdatePatientProfile message when processing case or before login!!!");
            return;
        }

    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selectPatient = new javax.swing.JButton();
        patientID = new javax.swing.JLabel();
        patientName = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        txt_pID = new java.awt.TextField();
        txt_pDoB = new java.awt.TextField();
        txt_pName = new java.awt.TextField();
        jPanel5 = new javax.swing.JPanel();
        txt_heartRate = new javax.swing.JTextField();
        txt_weight = new javax.swing.JTextField();
        weight = new javax.swing.JLabel();
        pressure = new javax.swing.JLabel();
        txt_height = new javax.swing.JTextField();
        txt_high = new javax.swing.JTextField();
        txt_systole = new javax.swing.JTextField();
        lowPressure = new javax.swing.JLabel();
        heartRate = new javax.swing.JLabel();
        highPressure = new javax.swing.JLabel();
        height = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        VisitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GetMD Nurse");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(470, 600));
        getContentPane().setLayout(null);

        selectPatient.setText("Click Here to Select Existing Patient");
        selectPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPatientActionPerformed(evt);
            }
        });

        patientID.setText("Patient ID:");

        patientName.setText("Patient Name:");

        DOB.setText("Date of Birth:");

        txt_pID.setEditable(false);
        txt_pID.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txt_pIDTextValueChanged(evt);
            }
        });

        txt_pDoB.setEditable(false);

        txt_pName.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(selectPatient)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientName)
                                    .addComponent(patientID))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(DOB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_pDoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_pName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientID)
                    .addComponent(txt_pID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOB)
                    .addComponent(txt_pDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 60, 310, 150);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient's Vital Sign", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 18))); // NOI18N

        weight.setText("Weight (Pounds):");

        pressure.setText("Blood Pressure (mmHg):");

        txt_height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_heightActionPerformed(evt);
            }
        });

        lowPressure.setText("Systole");

        heartRate.setText("Heart Rate (bpm):");

        highPressure.setText("Diastole");

        height.setText("Height (Inches):");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(heartRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_heartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(height)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_height, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pressure)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(weight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(highPressure)
                            .addComponent(txt_high, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lowPressure)
                            .addComponent(txt_systole, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(height)
                    .addComponent(txt_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weight)
                    .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pressure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(highPressure)
                    .addComponent(lowPressure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_systole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_high, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heartRate)
                    .addComponent(txt_heartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(30, 220, 360, 217);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(30, 450, 137, 23);

        VisitButton.setText("Add Patient to Visit");
        VisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VisitButton);
        VisitButton.setBounds(180, 450, 159, 23);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(360, 450, 80, 23);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Nurse Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 214, 37);

        jLabel3.setMinimumSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 10, 450, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPatientActionPerformed
           

        JFrame jf = new JFrame();
 

        String[] name={"ID","NAME","GENDER"};
        String[] s1 = { "0", "Amami Haruka" , "female"};
        String[] s2 = { "1", "Kisaragi Chihaya" , "female"};
        String[] s3 = { "2", "Hagiwara Yukiho" , "female"};
        String[] s4 = { "3", "Takatsuki Yayoyi" , "female"};
        String[] s5 = { "4", "Miura Azusa" , "female"};
        String[] s6 = { "5", "Minase Iori" , "female"};
        String[] s7 = { "6", "Kikuchi Makoto" , "female"};
        String[] s8 = { "7", "Futami Ami" , "female"};
        String data[][] = { s1, s2 , s3, s4, s5, s6, s7, s8};
        JTable table = new JTable(data,name);
        JScrollPane JSP= new JScrollPane(table);
        jf.add(JSP);
        jf.setTitle("Patient");
        jf.setBounds(300, 500, 500, 300);
        jf.setVisible(true);
         // TODO add your handling code here:
                // TODO add your handling code here:
    }//GEN-LAST:event_selectPatientActionPerformed

    private void txt_heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_heightActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
         
        dispose();        // TODO add your handling code here:
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    
    //databse
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
//               try{
//                   PatientInfo pi = nc.pi;
//                   addPatientInfo(pi);
//            } catch (Exception e) {
//            e.printStackTrace();
//        }  
               JOptionPane.showMessageDialog(null, "Patient's Information has been saved");
               dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void VisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Patient has been successfully added");
               dispose();
    }//GEN-LAST:event_VisitButtonActionPerformed

    private void txt_pIDTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txt_pIDTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pIDTextValueChanged

    /**
     * @param args the command line arguments
     */
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOB;
    private javax.swing.JButton VisitButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel heartRate;
    private javax.swing.JLabel height;
    private javax.swing.JLabel highPressure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lowPressure;
    private javax.swing.JLabel patientID;
    private javax.swing.JLabel patientName;
    private javax.swing.JLabel pressure;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton selectPatient;
    private javax.swing.JTextField txt_heartRate;
    private javax.swing.JTextField txt_height;
    private javax.swing.JTextField txt_high;
    private java.awt.TextField txt_pDoB;
    private java.awt.TextField txt_pID;
    private java.awt.TextField txt_pName;
    private javax.swing.JTextField txt_systole;
    private javax.swing.JTextField txt_weight;
    private javax.swing.JLabel weight;
    // End of variables declaration//GEN-END:variables
}
